#!/usr/bin/env Rscript

args <- commandArgs(trailingOnly = TRUE)
infile <- args[length(args)-5]
binProp <- args[length(args)-4]
bulkDF <- args[length(args)-3]
pathwayStr <- args[length(args)-2]
methodStr <- args[length(args)-1]
tissueStr <- args[length(args)]

if (!length(args) > 1) {
  stop("
Usage: crossTissueGO infile binProp bulkDF pathwayStr methodStr tissueStr
infile is Rdata workspace with GO terms (human Uniprot) loaded and formatted.
binProp (cell types by individuals) for the tissue of origin
bulkDF (genes by individuals) for the tissue of destination.
pathwayStr is a string to filter GO pathways of interest in destination tissue.
methodStr is the method of interest, used to filter, and as label for plots.
tissueStr is the tissue of destination, used as label for plots."
    )
}

library(dplyr)
library(ggplot2)
library(WGCNA)
library(mclust)

binPropcsv = read.csv(binProp, header=TRUE)
row.names(binPropcsv) = binPropcsv$X
binPropcsv$X = NULL
DeconBulk = binPropcsv[grepl(methodStr, binPropcsv$method),]
row.names(DeconBulk) = gsub("[0-9]$", "", row.names(DeconBulk))
bulkDFcsv = read.csv(bulkDF, header=TRUE)
bulkDFcsv = bulkDFcsv[!is.na(bulkDFcsv$X),]
row.names(bulkDFcsv) = bulkDFcsv$X
bulkDFcsv$X = NULL

load(infile)

IntersectGOterms = function(DeconBulkDF, bulkGenesDF, pathwayStr, methodStr, tissueStr) {
  cellAbundances = as.data.frame(t(DeconBulkDF))
  bulkComp = as.data.frame(t(bulkGenesDF))
  cellAbundances = cellAbundances[row.names(cellAbundances) %in% row.names(bulkComp),]
  if (isTRUE(row.names(cellAbundances)[5] == row.names(bulkComp)[5])==F) {
    stop('Check your input dataframes! They should have individuals as columns.')
  }

  pathwayGeneList = go_terms[grepl(pathwayStr, go_terms$Gene.ontology..biological.process.),]
  targetPathwayGenes = bulkComp[,colnames(bulkComp) %in% pathwayGeneList$Gene.names...primary..]

  cors_table = bicorAndPvalue(cellAbundances, targetPathwayGenes, use = 'p')
  melted_cors_table = reshape2::melt(cors_table$bicor)
  melted_cors_table$Var2=NULL
  colnames(melted_cors_table) = c('CellType', 'bicor')
  pval1 = reshape2::melt(cors_table$p)
  melted_cors_table$pvalue = pval1$value
  ggplot(melted_cors_table, aes(x=CellType, y=-log10(pvalue), fill=CellType)) + ggtitle(paste0(pathwayStr)) + geom_violin() + geom_boxplot(width=0.1) + theme_classic() + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
  ggsave(paste0(tissueStr, "GO_", methodStr, "_", pathwayStr, ".png"), path=paste0(tissueStr, "GO"), width=8, height=6, units="in")}

IntersectGOterms(DeconBulk, bulkDFcsv, pathwayStr, methodStr, tissueStr)

quit()
