#!/usr/bin/env Rscript

args <- commandArgs(trailingOnly = TRUE)
infile <- args[-length(args)]
outfile <- args[length(args)]

if (!length(args) > 1) {
  stop("
Usage: GTExTissuesCheck infile outfile
Infile is Rdata workspace with GTEx bulk data loaded and formatted.
Outfile is table of GTEx tissues that can be queried."
    )
}

load(infile)
GTExTissues = strsplit(colnames(GTEx_full), "_")
GTExTissues = unique(sapply(GTExTissues, "[[", 2))

write.table(GTExTissues, outfile, sep="\t", quote=F)
