#!/usr/bin/env Rscript

args <- commandArgs(trailingOnly = TRUE)
infile <- args[-length(args)]
outfile <- args[length(args)]

if (!length(args) > 1) {
  stop("
Usage: GTExTissuesCheck infile outfile
Infile is GTEx_subfiltered.Rdata workspace with GTEx bulk data loaded, filtered, and formatted.
Outfile is table of GTEx tissue labels that can be queried."
    )
}

library(dplyr)

load(infile)
GTExTissues = unique(strsplit(row.names(GTEx_subfiltered), "_") %>% sapply("[[", 2))
write.table(GTExTissues, outfile, sep="\t", quote=F)
